### ISSUE TITLE
Add LICENSE.md

### ISSUE THREAD

**Issue by scottzach1** [danilocastronz/weldev-project-react-mui-ts-bp#1]
Hi Danilo Castro,

Thank you for the awesome tutorial! 😀

I would like to build one of my projects from this boilerplate. Unfortunately, I can't seem to see any license specified for this project. Would you be happy to add a license to the repository or clarify how you intend for others to use this project in the future?

Cheers!

ps. Hi from New Zealand as well!

**Comment by danilocastronz** [comment]
Hey @scottzach1 ,

I'm so happy with your feedback, mate! I really appreciate it 😃 

Sure thing, that's a great point actually! Yeah, the idea is 100% to make this repo open and free for everyone to use. I'll include the license right away!

Thanks again, Zac! and nice to me you 👍 

Cheers!

**Comment by scottzach1** [comment]
That was quick! 

Awesome, thank you very much! 😀.

**Comment by scottzach1** [comment]
Resolved via 97cd9ea3fcbeba8583defff8104b6502074764d7
