### ISSUE TITLE
Dependency issues when running npm install

### ISSUE THREAD

**Issue by brian-t-otts** [danilocastronz/weldev-project-react-mui-ts-bp#2]
I just cloned the project and ran `npm i`. No changes were made. Here's a screenshot below:

![image](https://user-images.githubusercontent.com/87823379/127758738-aeb81d02-c019-4fe3-8d02-104370fe593b.png)

**Comment by danilocastronz** [comment]
Hey @brian-t-otts , thanks for reaching out with this issue!

Please, could you run `npm i --force` and verify if it works?

Looking forward to hearing back from you!

Cheers,
Dan

**Comment by brian-t-otts** [comment]
Hi Dan,

Forcing the install worked. I saw that was a possible solution but wanted to let you know about the problem anyway. Thanks for getting back so quickly.

**Comment by danilocastronz** [comment]
Very much appreciated, Brian :) I did try to replicate the issue on my side, but no luck. Glad it's working, mate!
