### ISSUE TITLE
Console Warnings

### ISSUE THREAD

**Issue by mulibu-flyingk** [danilocastronz/weldev-project-react-mui-ts-bp#5]
Hi Dan,

first of all, I love your boilerplate! I am new to react but your template really got me a head start.
While writing my own little bits of code I have noticed that there are 4 warnings in the console (even without any changes from my side). 

1. React is complaining about "Each child in a list should have a unique "key" prop." which is related to Routes
2.  React does not recognize the `isSelected` (or isEnabled) prop on a DOM element, which should be related to StyledListItemButton from RouteItems

Being new to react I am unable to sort them out. Do you have any ideas how to get rid of them?

Cheers
Chris

![react_warnings_console](https://user-images.githubusercontent.com/3972733/142428614-a6c13d95-1414-4163-9597-c5891020dab8.png)

**Comment by danilocastronz** [comment]
Hey Chris,

**Comment by danilocastronz** [comment]
Hey @mulibu-flyingk , I've fixed those console warnings. Here's the explanation for each of them:
1. "React is complaining about "Each child in "": On `src\components\Navigation\Routes\index.tsx` row 27, it was added a key reference to the DIV element. If you want to learn more about it, here is the documentation page: https://reactjs.org/docs/lists-and-keys.html
2. "React does not recognize the isSelected ": It's a warning about using custom DOM elements' properties (i.e., isSelected and isEnabled). The reason we use those is to pass custom values to the Emotion styled components. React suggests some alternatives such as naming the props using lowercase. I reckon this warning can be ignore for the scenario.

Please, let me know if you have any questions mate!
