### ISSUE TITLE
React does not recognize the `isSelected` prop on a DOM element.

### ISSUE THREAD

**Issue by sunnykandev** [danilocastronz/weldev-project-react-mui-ts-bp#6]
Warning: React does not recognize the `isSelected` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isselected` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

**Comment by danilocastronz** [comment]
Thank you, @sunnykandev . I'm working on this. I'll push a new PR shortly.
